# Generated by Django 4.1.5 on 2023-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logitem',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='function',
            field=models.CharField(max_length=255),
        ),
    ]
